version: '3.8'

volumes:
  postgres_db_vol:

services:
  dt_postgres:
    # Database to store all vector data, states, and links to raster data.
    image: postgis/postgis
    container_name: cont_dt_postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_db_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U $POSTGRES_USER -d $POSTGRES_DB

  dt_backend:
    # Performs analysis, computation, handles web requests, facilitates database interactions
    image: digital-twins-backend
    container_name: cont_dt_backend
    build:
      context: docker
      args:
        - WITH_SUDO=yes
    env_file:
      - .env
      - .env.docker-override
    ports:
      - "5000:5000"
    volumes:
      - "./workspace:/home/jovyan"
      - "../FloodRiskResearch:/home/jovyan/FloodRiskResearch"
    depends_on:
      - dt_postgres
      - dt_message_broker
      - dt_geoserver
    extra_hosts:
      - "host.docker.internal:host-gateway"

# Celery worker removed temporarily because BG_flood has not yet been configured for docker.

  dt_geoserver:
    # Serves geospatial web data through interactions with files and database
    image: docker.osgeo.org/geoserver:2.21.2
    container_name: cont_dt_geoserver
    volumes:
      - "./workspace/Digital-Twins/geoserver/geoserver_data:/opt/geoserver_data"
    depends_on:
      - dt_postgres
    environment:
      - SKIP_DEMO_DATA=true
      - CORS_ENABLED=true
    ports:
      - "${GEOSERVER_PORT}:8080"
    restart: always
    healthcheck:
      test: curl --fail -s http://host.docker.internal:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

# WWW removed temporarily because build is failing and more work is needed.

  dt_message_broker:
    # Communicates between backend and workers to assign tasks and store state
    image: redis
    container_name: cont_dt_message_broker
    ports:
      - "6379:6379"
    restart: always

